### ISSUE TITLE
Loading Streaming

### ISSUE THREAD

**Issue by gomesgustavo** [roymacdonald/ofxSoundObjects#29]
Hi again,

I am trying to load 22 audios, for 22 channels.
Each of them have around 8 minutes, and it tooks more than a minute to load all the audios.

I saw the streaming parameter in the loading function at ofxSoundPlayerObject, but I also saw it is unavailable in the comments.

Is there any point where I can help to implement this, or is this an effort close to be implemented?

Cheers!

**Comment by roymacdonald** [comment]
Hi, yes, the streaming is not implemented in the player although it is in the ofxSoundFile, meaning the infrastructure is there. I think I already implemented it for an upcoming version I am working on, which I have not published yet because it will be non backwards compatible. I can take a look if I can add this to the current implementation.
Although, there is an async loading function which will load the files on a different thread, which will benefit a lot if you have a multicore computer. look at the example-matrixMixer which uses the async loading. You'll need to change [this line ](https://github.com/roymacdonald/ofxSoundObjects/blob/master/example-matrixMixer/src/ofApp.cpp#L87) to true so it works. Hope this helps

**Comment by roymacdonald** [comment]
hey @gomesgustavo I just updated the code for the sound player to support file streaming. Although I haven't tested it thoroughly. Streaming is only supported on wav files. To use it you just need to pass `true` after the filepath when calling `load(..)`. 
```
//ofxSoundPlayerObject player; // declared somewhere else
player.load("path/to/audio/file.wav", true);
```
Hope this helps. 
best

**Comment by gomesgustavo** [comment]
I apologize for the delay in giving you feedback Roy.
I'm doing some tests but you helped a lot. Thank you very much!!

**Comment by roymacdonald** [comment]
No problem.
Let me know how those tests go and if this feature needs any improvements or you bump into a bug or crash.
cheers

**Comment by gomesgustavo** [comment]
We are using the Motu 24Ao audio interface and Openframeworks version of_v0.10.1_vs2017_release.
We are also developing to a small for factor PC:
https://www.dell.com/pt-br/work/shop/computadores-all-in-ones-e-workstations/optiplex-3060-micro/spd/optiplex-3060-micro
The performance is amazing, and it is working very well.

The scope is basically to play independent audios on specific outputs. These audios should be in sync with an video.
After finishing the video, it should go to the next video and audios.
