### ISSUE TITLE
Multiple outputs are not working with a virtual soundcard.

### ISSUE THREAD

**Issue by fred-dev** [roymacdonald/ofxSoundObjects#35]
I am trying to do some testing with a virtual soundcard (Loopback) for multichannel work as I dont have access to a full setup right now.

I know this is may have nothing to do with ofxSoundobjects, but when i use a virtual soundcard as an output, I can run the example-soundPlayerMultiOutput fine, but when I try the example-matrixMixer the project compiles and runs but I dont get any output to the device. I am trying with an 8 channel output device I the only thing I see is this output:

`[verbose] ofxSoundObject: working buffer size != output buffer size. 0 != 4096
`
The metering on the app works, but no audio seems to pass to the output.

When I test with the 2 channel built in output of my macbook pro with the example-matrixMixer  project I also do not get any sound output.

When i use the built in hardware I get the following output:

```
[verbose] ofxSoundObject: working buffer size != output buffer size. 0 != 512
[warning] ofRtAudioSoundStream: stream over/underflow detected
```
I am on mac OS catalina 10.15.7.

Fred

**Comment by roymacdonald** [comment]
Hi, don't worry about those warnings as long as these show up only during the startup. The stream over/underflow it is telling that that audio processing is taking too long. If it happens once or twice it is not problematic but if you see it being printed a lot then it is not good and probably you will hear some glitches, pops and/or clicks.

As for the matrix mixer not sounding it is because the output volume of it is set to zero. This is because there is an input and it can cause an annoying audio feedback loop.
Just drag the sliders at the bottom of the matrix mixer as in the following screen cap.
<img width="1033" alt="Screen Shot 2021-04-18 at 20 47 04" src="https://user-images.githubusercontent.com/974878/115168044-a5587900-a087-11eb-900a-97f976096b61.png">

or set this sliders programatically.
```
		mixer.setOutputVolumeForChannel(float volume, size_t channel_index);
		mixer.setOutputVolumeForAllChannels(float volume);
```
on both cases the volume is normalized, from 0 to 1. channel_index start at 0

**Comment by fred-dev** [comment]
Ok, I totally missed that, thanks. I now get sound on my macbook pro speakers, something is not quite right with loopback, but I will investigate that further.

Thanks
