### ISSUE TITLE
Select API needed for windows

### ISSUE THREAD

**Issue by fred-dev** [roymacdonald/ofxSoundObjects#49]
This is a really great addon and does some amazing things for sound on OF. Are you still developing it? One issue that arrises is multiple API's on Windows. Your system seems to default to Asio, which is pretty good,  but not always appropriate. I have been messing around but am not a good coder. It would be great to have some system wide call for setApi that would narrow the API down for all calls that get and set in and out devices.

**Comment by roymacdonald** [comment]
Hi, thanks for the kind words. Yes, I am still developing, I mean I keep on adding/fixing stuff. I mostly develop on macos, so the windows side of it might be a bit left behind, and in macos there is a single sound API. The API is set for each ofSoundStream instance, which allows you to have several streams, from different devices and/or APIs. Because of this I dont think that having a "system wide" setApi call would work. But, besides that fact, all the setApi, in/out devices, etc, is part of openFrameworks sound system. My addon is simply making use of it; thus, what you are proposing should be part of the openFramworks sound implementation(hence opening an issue in OF's repo ). 
best.
