### ISSUE TITLE
maxtrixMixer file player not showing progress bar

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxSoundObjects#53]
In the latest version of this addon with OF 0.12 the little black progress bars are not appearing anymore. Here a video from what I had running in back with of-11.2 
https://github.com/roymacdonald/ofxSoundObjects/assets/1054816/38dfe7f5-3cce-481d-a894-ab61f9208827

**Comment by roymacdonald** [comment]
Hi @stephanschulz 
I had that feature disabled because it was causing a crash,
https://github.com/roymacdonald/ofxSoundObjects/commit/24fd255d8f17c87ee548aa5f5f2da0809dcb04a2

Although, I added it back. It is disabled by default but you can enable it.
I added the following functions to the matrix mixer renderer with which you can enable it.
https://github.com/roymacdonald/ofxSoundObjects/blob/master/src/Renderers/ofxSoundObjectMatrixMixerRenderer.h#L46-L54
